name: Pruebas Automatizadas

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: testdb
        options: >-
          --health-cmd "mongosh --eval 'db.serverStatus()'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Dar permisos a mvnw
        run: chmod +x ./mvnw
      
      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Esperar a MongoDB
        run: sleep 15
      
      - name: Ejecutar pruebas
        run: ./mvnw test
        env:
          SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/testdb